
title: Loop
tagline: Tales from the loop

remote_theme: LeNPaul/Millennial@gh-pages

paginate:            5

markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]


exclude:
  - README.md
